/**
 * App-controlled Expo modules provider.
 *
 * Keeps the autogenerated Expo module list under source control and extends it
 * with local app modules such as the live scanner.
 */

import ExpoModulesCore
import Expo
import EXApplication
import ExpoAsset
import EXAV
import ExpoBlur
import ExpoCalendar
import ExpoCamera
import ExpoClipboard
import EXConstants
import ExpoContacts
import ExpoCrypto
import ExpoDevice
import ExpoDocumentPicker
import ExpoFileSystem
import ExpoFont
import ExpoHaptics
import ExpoImageManipulator
import ExpoImagePicker
import ExpoKeepAwake
import ExpoLinearGradient
import ExpoLinking
import ExpoLocalAuthentication
import ExpoLocalization
import ExpoMailComposer
import ExpoMediaLibrary
import ExpoNetwork
import EXNotifications
import ExpoPrint
import ExpoHead
import ExpoSecureStore
import ExpoSensors
import ExpoSharing
import ExpoSpeech
import ExpoSQLite
import ExpoWebBrowser
#if EXPO_CONFIGURATION_DEBUG
import EXDevLauncher
import EXDevMenu
#endif

@objc(ExpoModulesProvider)
public class ExpoModulesProvider: ModulesProvider {
  public override func getModuleClasses() -> [AnyModule.Type] {
    #if EXPO_CONFIGURATION_DEBUG
    return [
      ExpoFetchModule.self,
      ApplicationModule.self,
      AssetModule.self,
      VideoViewModule.self,
      BlurViewModule.self,
      CalendarModule.self,
      CameraViewModule.self,
      ClipboardModule.self,
      ConstantsModule.self,
      ContactsModule.self,
      ContactAccessButtonModule.self,
      CryptoModule.self,
      DeviceModule.self,
      DocumentPickerModule.self,
      FileSystemModule.self,
      FileSystemLegacyModule.self,
      FontLoaderModule.self,
      FontUtilsModule.self,
      HapticsModule.self,
      ImageManipulatorModule.self,
      ImagePickerModule.self,
      KeepAwakeModule.self,
      LinearGradientModule.self,
      ExpoLinkingModule.self,
      LocalAuthenticationModule.self,
      LocalizationModule.self,
      MailComposerModule.self,
      MediaLibraryModule.self,
      MediaLibraryNextModule.self,
      NetworkModule.self,
      BackgroundModule.self,
      BadgeModule.self,
      CategoriesModule.self,
      EmitterModule.self,
      HandlerModule.self,
      PermissionsModule.self,
      PresentationModule.self,
      PushTokenModule.self,
      SchedulerModule.self,
      ServerRegistrationModule.self,
      ExpoPrintModule.self,
      ExpoHeadModule.self,
      LinkPreviewNativeModule.self,
      SecureStoreModule.self,
      AccelerometerModule.self,
      BarometerModule.self,
      DeviceMotionModule.self,
      GyroscopeModule.self,
      MagnetometerModule.self,
      MagnetometerUncalibratedModule.self,
      PedometerModule.self,
      SharingModule.self,
      SpeechModule.self,
      SQLiteModule.self,
      WebBrowserModule.self,
      DevMenuModule.self,
      DevMenuInternalModule.self,
      DevMenuPreferences.self,
      BriefPilotLiveScannerModule.self,
      BriefPilotScannerModule.self,
    ]
    #else
    return [
      ExpoFetchModule.self,
      ApplicationModule.self,
      AssetModule.self,
      VideoViewModule.self,
      BlurViewModule.self,
      CalendarModule.self,
      CameraViewModule.self,
      ClipboardModule.self,
      ConstantsModule.self,
      ContactsModule.self,
      ContactAccessButtonModule.self,
      CryptoModule.self,
      DeviceModule.self,
      DocumentPickerModule.self,
      FileSystemModule.self,
      FileSystemLegacyModule.self,
      FontLoaderModule.self,
      FontUtilsModule.self,
      HapticsModule.self,
      ImageManipulatorModule.self,
      ImagePickerModule.self,
      KeepAwakeModule.self,
      LinearGradientModule.self,
      ExpoLinkingModule.self,
      LocalAuthenticationModule.self,
      LocalizationModule.self,
      MailComposerModule.self,
      MediaLibraryModule.self,
      MediaLibraryNextModule.self,
      NetworkModule.self,
      BackgroundModule.self,
      BadgeModule.self,
      CategoriesModule.self,
      EmitterModule.self,
      HandlerModule.self,
      PermissionsModule.self,
      PresentationModule.self,
      PushTokenModule.self,
      SchedulerModule.self,
      ServerRegistrationModule.self,
      ExpoPrintModule.self,
      ExpoHeadModule.self,
      LinkPreviewNativeModule.self,
      SecureStoreModule.self,
      AccelerometerModule.self,
      BarometerModule.self,
      DeviceMotionModule.self,
      GyroscopeModule.self,
      MagnetometerModule.self,
      MagnetometerUncalibratedModule.self,
      PedometerModule.self,
      SharingModule.self,
      SpeechModule.self,
      SQLiteModule.self,
      WebBrowserModule.self,
      BriefPilotLiveScannerModule.self,
      BriefPilotScannerModule.self,
    ]
    #endif
  }

  public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
    return [
      FileSystemBackgroundSessionHandler.self,
      LinkingAppDelegateSubscriber.self,
      NotificationsAppDelegateSubscriber.self,
      ExpoHeadAppDelegateSubscriber.self,
    ]
  }

  public override func getReactDelegateHandlers() -> [ExpoReactDelegateHandlerTupleType] {
    return []
  }

  public override func getAppCodeSignEntitlements() -> AppCodeSignEntitlements {
    return AppCodeSignEntitlements.from(json: #"{}"#)
  }
}
