import { StyleSheet } from 'react-native';
import { ACCENT } from '@/features/scan/constants';

export const advancedBatchStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  title: { color: '#fff', fontSize: 18, fontWeight: '700' },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  infoBox: {
    marginHorizontal: 14,
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  infoText: { color: 'rgba(255,255,255,0.75)', fontSize: 12 },
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  smallBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  smallBtnText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  actionBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ACCENT,
    flexDirection: 'row',
    gap: 6,
  },
  actionText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  disabled: { opacity: 0.35 },
  listTitle: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 14,
    marginVertical: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
    borderRadius: 12,
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  rowSelected: { borderColor: ACCENT, backgroundColor: `${ACCENT}20` },
  thumb: { width: 52, height: 70, borderRadius: 8, backgroundColor: '#111' },
  rowTitle: { color: '#fff', fontSize: 14, fontWeight: '700' },
  rowSub: { color: 'rgba(255,255,255,0.65)', fontSize: 11 },
  rowBtns: { gap: 6 },
  undoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(11,13,22,0.98)',
  },
  undoTitle: { color: '#fff', fontSize: 13, fontWeight: '700' },
  undoHint: { color: 'rgba(255,255,255,0.7)', fontSize: 11, marginTop: 2 },
  undoBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: ACCENT,
  },
  undoBtnText: { color: '#fff', fontSize: 12, fontWeight: '800' },
});
